### PR TITLE
componentList is an optional element in mzML

### PR DESCRIPTION
**Pull request by heckendorfc**
As titled. I ran into a case where it didn't exist in the mzML file.

### CODE REVIEW

**Comment by mobiusklein** [comment]
`_convert_component_groups`  does more than it should, building the `InstrumentInformation` instance. We either need to break the method up, or move the check into `_convert_component_groups`.

**Comment by heckendorfc** [comment]
I see that now; I'll move the check inside. I'm not sure if there's any reason to break the method up further but maybe renaming it would make sense.

**Comment by mobiusklein** [comment]
Sounds good. How about something like `_pack_instrument_information`?

**Comment by mobiusklein** [comment]
Fixed the naming issue in commit ce9f915f200093058baddf6ffa74656e6e1006c6

**Pull request merged**
